### PR TITLE
Respect dark preference

### PR DESCRIPTION
**Pull request by davidmhewitt**
Uses Granite to read and listen for changes to the user's dark style preference. I've essentially written the Granite parts in C, rather than gtkmm style C++ since there aren't gtkmm bindings for Granite.

### CODE REVIEW

**Comment by JeysonFlores** [comment]
Yep, I thought that in order to use Granite or Handy I'd have to use C code.

**Comment by JeysonFlores** [comment]
For some reason always that I try to execute this code locally, it can't localize `<granite.h>` but it seems that it has been passed all the checks. Do you know what would be the problem?

**Comment by davidmhewitt** [comment]
Can you post the output you see?

**Comment by JeysonFlores** [comment]
The output is:
```bash
FAILED: com.github.jeysonflores.elementarycpp@exe/src_Application.cpp.o 
c++ -Icom.github.jeysonflores.elementarycpp@exe -I. -I.. -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include 
-I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include 
-I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-
gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/at-spi2-atk/2.0
-I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-
nix-2.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr
/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 
-I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr
/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always 
-pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=gnu++17 -g -pthread -MD -MQ 
'com.github.jeysonflores.elementarycpp@exe/src_Application.cpp.o' -MF 'com.github.jeysonflores.elementarycpp@exe/src_Application.cpp.o.d' -o 
'com.github.jeysonflores.elementarycpp@exe/src_Application.cpp.o' -c ../src/Application.cpp
In file included from ../src/Application.cpp:1:
../src/Application.h:4:10: fatal error: granite.h: File or directory does not exist
    4 | #include <granite.h>
      |          ^~~~~~~~~~~
compilation terminated.
```
I have the elementary-sdk package installed and everything up-to-date, and this happens even in the flatpak building of the app.
Also, `granite.h` is in the directory `/usr/include/granite`

**Comment by davidmhewitt** [comment]
I don't see `-I/usr/include/granite` in your compiler log there which means meson/ninja isn't telling the compiler to look in that include directory for some reason.

It works perfectly on my PC with and without Flatpak, and it has also worked in the checks that have run in GitHub actions, so I would suggest deleting all of your local build/code folders, pulling the branch again and trying again.

**Comment by JeysonFlores** [comment]
Some time ago I did some header-related tricks in order to be able to use a C++ library, perhaps I did something I shouldn't had to do. 
The code looks good, it works to you and the checks,  so I think I'll merge this pull request.

**Pull request merged**
